services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: python:alpine
    container_name: app

  lint:
    build:
      context: .
      dockerfile: ./services/lint/Dockerfile
      args:
        BASE_IMAGE: python:alpine
        TOOL: flake8
        TOOL_VERSION: 7.1.1
    entrypoint: ["flake8"]
    working_dir: /app
    container_name: lint

  format:
    build:
      context: .
      dockerfile: ./services/format/Dockerfile
      args:
        BASE_IMAGE: python:alpine
        TOOL: black
        TOOL_VERSION: 23.3.0
    volumes:
      - ./app:/app
      - ./tests:/tests
    entrypoint: ["black"]
    command: ["/app", "/tests"]
    working_dir: /app
    container_name: format

  test:
    build:
      context: .
      dockerfile: ./services/test/Dockerfile
      args:
        BASE_IMAGE: python:alpine
        TOOL: pytest
        TOOL_VERSION: 8.3.2
    entrypoint: ["pytest"]
    working_dir: /app
    container_name: test

  sast:
    build:
      context: .
      dockerfile: ./services/sast/Dockerfile
      args:
        BASE_IMAGE: python:alpine
        TOOL: bandit
        TOOL_VERSION: 1.7.5
    volumes:
      - ./app:/app
      - ./tests:/tests
    entrypoint: ["bandit"]
    command: ["-r", "/app"]
    working_dir: /app
    container_name: bandit
